name: CI Tests

on:
  push:
    branches: [live]
  pull_request:
    branches: [live]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make test-ci
        run: make test-ci
