name: CI Tests

on:
  push:
    branches: [live]
  pull_request:
    branches: [live]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with make
        run: make test-ci
